version: "3"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"

  my_blog:
    build: ./my_blog
    container_name: my_blog_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
